#!/bin/sh

docker run \
  -u "$(id -u):$(id -g)" \
  --rm \
  -v ${PWD}:/local \
  openapitools/openapi-generator-cli \
  generate \
  -g python-legacy \
  --library asyncio \
  --package-name idbroker.provisioning_api \
  -i /local/src/plugins/packages/idbroker/provisioning_openapi.json \
  -o /local/src/plugins/packages \
  --additional-properties=generateSourceCodeOnly=true \
  --additional-properties=packageVersion=$(cat src/plugins/packages/idbroker/VERSION.txt) \
  --global-property=apiTests=false \
  --global-property=modelTests=false
