sonar.projectKey=univention_dev_education_ucsschool-id-connector_edee809d-6df6-4c3d-b128-437c22f04667
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=src/tests
