# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import idbroker.provisioning_api
from idbroker.provisioning_api.api.users_api import UsersApi  # noqa: E501
from idbroker.provisioning_api.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = idbroker.provisioning_api.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_ucsschool_apis_provisioning_v1_school_authority_users_user_id_delete(self):
        """Test case for delete_ucsschool_apis_provisioning_v1_school_authority_users_user_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_get_head_ucsschool_apis_provisioning_v1_school_authority_users_user_id_head(self):
        """Test case for get_head_ucsschool_apis_provisioning_v1_school_authority_users_user_id_head

        Get Head  # noqa: E501
        """
        pass

    def test_get_ucsschool_apis_provisioning_v1_school_authority_users_user_id_get(self):
        """Test case for get_ucsschool_apis_provisioning_v1_school_authority_users_user_id_get

        Get  # noqa: E501
        """
        pass

    def test_post_ucsschool_apis_provisioning_v1_school_authority_users_post(self):
        """Test case for post_ucsschool_apis_provisioning_v1_school_authority_users_post

        Post  # noqa: E501
        """
        pass

    def test_put_ucsschool_apis_provisioning_v1_school_authority_users_user_id_put(self):
        """Test case for put_ucsschool_apis_provisioning_v1_school_authority_users_user_id_put

        Put  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
