# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import idbroker.provisioning_api
from idbroker.provisioning_api.api.auth_api import AuthApi  # noqa: E501
from idbroker.provisioning_api.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = idbroker.provisioning_api.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_for_access_token_ucsschool_apis_auth_token_post(self):
        """Test case for login_for_access_token_ucsschool_apis_auth_token_post

        Login For Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
