# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import idbroker.provisioning_api
from idbroker.provisioning_api.models.school_class import SchoolClass  # noqa: E501
from idbroker.provisioning_api.rest import ApiException

class TestSchoolClass(unittest.TestCase):
    """SchoolClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchoolClass
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = idbroker.provisioning_api.models.school_class.SchoolClass()  # noqa: E501
        if include_optional :
            return SchoolClass(
                name = '0', 
                description = '', 
                school = '0', 
                members = [
                    '0'
                    ]
            )
        else :
            return SchoolClass(
                name = '0',
                description = '',
                school = '0',
                members = [
                    '0'
                    ],
        )

    def testSchoolClass(self):
        """Test SchoolClass"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
