# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import idbroker.provisioning_api
from idbroker.provisioning_api.api.schools_api import SchoolsApi  # noqa: E501
from idbroker.provisioning_api.rest import ApiException


class TestSchoolsApi(unittest.TestCase):
    """SchoolsApi unit test stubs"""

    def setUp(self):
        self.api = idbroker.provisioning_api.api.schools_api.SchoolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_head_ucsschool_apis_provisioning_v1_school_authority_schools_name_head(self):
        """Test case for get_head_ucsschool_apis_provisioning_v1_school_authority_schools_name_head

        Get Head  # noqa: E501
        """
        pass

    def test_get_ucsschool_apis_provisioning_v1_school_authority_schools_name_get(self):
        """Test case for get_ucsschool_apis_provisioning_v1_school_authority_schools_name_get

        Get  # noqa: E501
        """
        pass

    def test_post_ucsschool_apis_provisioning_v1_school_authority_schools_post(self):
        """Test case for post_ucsschool_apis_provisioning_v1_school_authority_schools_post

        Post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
