# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import idbroker.provisioning_api
from idbroker.provisioning_api.models.school import School  # noqa: E501
from idbroker.provisioning_api.rest import ApiException

class TestSchool(unittest.TestCase):
    """School unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test School
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = idbroker.provisioning_api.models.school.School()  # noqa: E501
        if include_optional :
            return School(
                name = '0', 
                display_name = '0'
            )
        else :
            return School(
                name = '0',
                display_name = '0',
        )

    def testSchool(self):
        """Test School"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
