skinparam backgroundColor white
skinparam defaultTextAlignment center

skinparam AgentBackgroundColor  #009646
skinparam AgentFontColor white
skinparam AgentBorderColor #6a8198

skinparam FolderBackgroundColor #bdbdbb
skinparam StorageBackgroundColor #7AB51D
skinparam DatabaseBackgroundColor #bdbdbb

skinparam NoteBackgroundColor white
skinparam NoteFontColor grey
skinparam NoteBorderColor darkgrey

skinparam FileBackgroundColor d8d8d6
skinparam UsecaseBackgroundColor white
skinparam UsecaseFontColor #777777
skinparam UsecaseBorderColor grey

skinparam ArrowColor #666666
skinparam ArrowFontColor #666666

skinparam FrameBackgroundColor   #ededed
