skinparam backgroundColor white
skinparam defaultTextAlignment center

skinparam AgentBackgroundColor  #81c95b
skinparam AgentFontColor black
skinparam AgentBorderColor #6a8198

skinparam FolderBackgroundColor #bbbbbb
skinparam FolderFontColor black
skinparam StorageBackgroundColor #349400
skinparam StorageFontcolor white
skinparam DatabaseBackgroundColor #bbbbbb
skinparam DatabaseFontColor black

skinparam NoteBackgroundColor white
skinparam NoteFontColor grey
skinparam NoteBorderColor darkgrey

skinparam FileBackgroundColor d8d8d6
skinparam UsecaseBackgroundColor white
skinparam UsecaseFontColor #777777
skinparam UsecaseBorderColor grey

skinparam ArrowColor #666666
skinparam ArrowFontColor #666666

skinparam FrameBackgroundColor   #ededed



' https://colorschemedesigner.com/csd-3.5/#2F11T--llw0w0
' 349400 396f1c 226000 67c932 81c95b
