# coding: utf-8

# flake8: noqa
"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from idbroker.provisioning_api.models.http_validation_error import HTTPValidationError
from idbroker.provisioning_api.models.school import School
from idbroker.provisioning_api.models.school_class import SchoolClass
from idbroker.provisioning_api.models.school_context import SchoolContext
from idbroker.provisioning_api.models.token import Token
from idbroker.provisioning_api.models.user import User
from idbroker.provisioning_api.models.validation_error import ValidationError
