# coding: utf-8

"""
    UCS@school APIs

    This application exposes network resources introduced via custom plugins.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from idbroker.provisioning_api.configuration import Configuration


class SchoolClass(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'description': 'str',
        'school': 'str',
        'members': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'school': 'school',
        'members': 'members'
    }

    def __init__(self, name=None, description=None, school=None, members=None, local_vars_configuration=None):  # noqa: E501
        """SchoolClass - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._description = None
        self._school = None
        self._members = None
        self.discriminator = None

        self.name = name
        self.description = description
        self.school = school
        self.members = members

    @property
    def name(self):
        """Gets the name of this SchoolClass.  # noqa: E501


        :return: The name of this SchoolClass.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SchoolClass.


        :param name: The name of this SchoolClass.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this SchoolClass.  # noqa: E501


        :return: The description of this SchoolClass.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SchoolClass.


        :param description: The description of this SchoolClass.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def school(self):
        """Gets the school of this SchoolClass.  # noqa: E501


        :return: The school of this SchoolClass.  # noqa: E501
        :rtype: str
        """
        return self._school

    @school.setter
    def school(self, school):
        """Sets the school of this SchoolClass.


        :param school: The school of this SchoolClass.  # noqa: E501
        :type school: str
        """
        if self.local_vars_configuration.client_side_validation and school is None:  # noqa: E501
            raise ValueError("Invalid value for `school`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                school is not None and len(school) < 1):
            raise ValueError("Invalid value for `school`, length must be greater than or equal to `1`")  # noqa: E501

        self._school = school

    @property
    def members(self):
        """Gets the members of this SchoolClass.  # noqa: E501


        :return: The members of this SchoolClass.  # noqa: E501
        :rtype: list[str]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this SchoolClass.


        :param members: The members of this SchoolClass.  # noqa: E501
        :type members: list[str]
        """
        if self.local_vars_configuration.client_side_validation and members is None:  # noqa: E501
            raise ValueError("Invalid value for `members`, must not be `None`")  # noqa: E501

        self._members = members

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SchoolClass):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SchoolClass):
            return True

        return self.to_dict() != other.to_dict()
