' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
        agent "<b>Management REST API\n<i>fastapi\n\nCRUD sync target configs\nand queues" as management_api
@enduml
