' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
    agent "<b>In queue\n<i>python process\n\nReads uuid\nWrites UDM objects JSON" as daemon
@enduml
