' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
    folder "<b>Small in-queue\n<i>JSON files\n\njust entryUUIDs" as small_queue
@enduml
