' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml

    frame "<b>ID Connector\n<i>Docker\n\nsyncs user data" as id_connector
@enduml
