' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
    frame "<b>UCS DC\n<i>UCS\n\nBasic user operations" as primary {
}
@enduml
