' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
     usecase "<b>School authority B\n<i>UCS / Kelvin\n\nManages schools" as school_provider_b
@enduml
