' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
     agent "<b>Out A\n<i>Kelvin plugin process\n\nsends to Kelvin API" as out_a
@enduml
