' SPDX-FileCopyrightText: 2021-2023 Univention GmbH
'
' SPDX-License-Identifier: AGPL-3.0-only

@startuml
    !include styling.puml
    folder "<b>Out queue B\n<i>JSON\n\nuser/group data" as out_queue_b
@enduml
